### ISSUE TITLE
Provide file name in skipped expression warning

### ISSUE THREAD

**Issue by dermeck** [43081j/postcss-styled-components#3]
Thank you for your work on this! Thanks to you I was able to update to v14 with emotion. :) The update was smooth but I noticed the following issue:

When the CSS block contains a comment with `//` it now produces a warning like. 
```
 [postcss-lit] Skipping template (Line 74) as it included either invalid syntax or complex expressions the plugin could not interpret. Consider using a "// postcss-lit-disable-next-line" comment to disable this message
```
(https://github.com/43081j/postcss-js-core/blob/master/src/parse.ts#L75 )

Before the same code resulted in a `CssSyntaxError` which also pointed to the file that caused the error. 
```
FileName.tsx
 74:21  ✖  Unknown word   CssSyntaxError
```

I'm not sure if it is possible and useful (since it's a broader case) to produce this error from within the custom synthax. But I think it would be helpful to also include the filename in the console warning so that the related code can be tracked down more easily.

**Comment by 43081j** [comment]
You're right, it should contain the file name. 

Do you have an example of some code which causes that error for you? Curious as maybe that's also fixable separately, assuming it is actually valid code in what you're using

**Comment by dermeck** [comment]
Yeah I was uncertain if it should be considered valid.

A minimal example would be:
```
const MyDiv = styled.div`
    height: 100%; // problematic comment
`;
```

(my actual code is this: https://github.com/dermeck/feeds-sidebar/commit/2621048235973b53bfc5bc85566318f7b74f92e6 )

**Comment by 43081j** [comment]
ah yeah unless sass/less/something else supports single line comments, the underlying css parser will complain.

we should still have a better error though, ill take a look at that
